Добавление баланса в кпк
Vonsant/corvax-frontier-14 pull request #208
Opened 2024-05-22 17:47 UTC by user424242420

## About the PR

## Why / Balance

## How to test

## Media

![image](https://github.com/Corvax-Frontier/corvax-frontier-14/assets/142989209/40f9f26d-f854-4c87-a20c-ec3be166f42c)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: Добавлен баланс в кпк

2024-05-22 17:55 UTC, FireNameFN requested changes

2024-05-22 17:55 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +        private string _balance = Loc.GetString("comp-pda-ui-balance", ("balance", 0));
Все выше получают "comp-pda-ui-unknown"

2024-05-22 17:55 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +
Очень важная строка

2024-05-22 17:55 UTC, FireNameFN commented on Content.Server/PDA/PdaSystem.cs
> +            }
Не по конвенциям стоят {.
Да и не нужны они, когда одна строчка.
Да и ифы можно объединить.
И тебе следует использовать тот тип, что у тебя в bank.Balance, а не ulong

2024-05-22 17:55 UTC, FireNameFN commented on Resources/Locale/en-US/pda/pda-component.ftl
> +comp-pda-ui-balance = Balance: [color=white]{ $balance }[/color]
Обычно для Корвакс фич не делают английскую локализацию

2024-05-22 17:55 UTC, FireNameFN commented on Content.Shared/PDA/PdaUpdateState.cs
> +        public ulong Balance;
Про типы я уже говорил. Просто напоминаю.

2024-05-22 17:57 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +        private string _balance = Loc.GetString("comp-pda-ui-balance", ("balance", 0));
А ещё ты пустую строку украл

2024-05-22 17:59 UTC, FireNameFN commented
И в следующий раз можешь удалить мусор из первого комментария

> ## About the PR
> ## Why / Balance
> ## How to test
> ## Media
> ![image](https://private-user-images.githubusercontent.com/142989209/332904960-40f9f26d-f854-4c87-a20c-ec3be166f42c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MDA5NDAsIm5iZiI6MTcxNjQwMDY0MCwicGF0aCI6Ii8xNDI5ODkyMDkvMzMyOTA0OTYwLTQwZjlmMjZkLWY4NTQtNGM4Ny1hMjBjLWVjM2JlMTY2ZjQyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNzU3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDc0NmUwYzQ5NTBiNzJjZGVmZjNmMWY2MWIwYWIzZTRjOTg1NGExNWE5NGM5MmUzMTBjZjMxOGE5MjNjMTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LN3_JK0ONiBl5EPjAyukvnvcE2k7yOM0Ls7yewWVgCk)
> 
> * [x]  I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> ## Breaking changes
> **Changelog**
> 
> * add: Добавлен баланс в кпк

2024-05-22 18:02 UTC, user424242420 commented on Content.Server/PDA/PdaSystem.cs
> +            }
нельзя, зачем исполнять второе если первое нулл

2024-05-22 18:02 UTC, user424242420 commented on Content.Client/PDA/PdaMenu.xaml.cs
> +        private string _balance = Loc.GetString("comp-pda-ui-balance", ("balance", 0));
> А ещё ты пустую строку украл

И зачем она?

2024-05-22 18:03 UTC, user424242420 commented on Content.Shared/PDA/PdaUpdateState.cs
> +        public ulong Balance;
> Про типы я уже говорил. Просто напоминаю.

Тип улонг потому что планируется улонг везде по причинам описанным здесь https://github.com/new-frontiers-14/frontier-station-14/pull/1363

2024-05-22 18:09 UTC, user424242420 commented on Resources/Locale/en-US/pda/pda-component.ftl
> +comp-pda-ui-balance = Balance: [color=white]{ $balance }[/color]
И че? Нельзя?

2024-05-22 18:39 UTC, FireNameFN commented on Content.Server/PDA/PdaSystem.cs
> +            }
```cs
if (actor_uid != null && TryComp<BankAccountComponent>(actor_uid, out var bank))
    balance = (ulong)bank.Balance;
```

2024-05-22 19:17 UTC, FireNameFN commented on Content.Server/PDA/PdaSystem.cs
> +            }
И лучше bank переименуй а account, ведь он там главное слово

2024-05-23 08:05 UTC, FireNameFN requested changes

2024-05-23 08:05 UTC, ProtoFN commented on Content.Server/PDA/PdaSystem.cs
> +
Объедини ифы и переименуй bank в account

2024-05-23 08:06 UTC, user424242420 commented on Content.Server/PDA/PdaSystem.cs
> +
Зачем ифы объединять ведь если actor uid == null то не имеет смысла выполнять поиск TryComp

2024-05-23 11:37 UTC, ProtoFN approved these changes

2024-05-23 18:30 UTC, merged