Время до эвака в кпк
Vonsant/corvax-frontier-14 pull request #210
Opened 2024-05-24 16:02 UTC by user424242420

## About the PR
Вообщем. Время до эвака в кпк
## Media

![image](https://github.com/Corvax-Frontier/corvax-frontier-14/assets/142989209/c41f70f1-d8b5-4280-95b6-4a762a98738f)
![image](https://github.com/Corvax-Frontier/corvax-frontier-14/assets/142989209/26876bd9-accc-4eb5-ba4a-3502e67a4ce3)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

add: Время до эвака в кпк
add: добавил знак доллара в баланс

2024-05-24 16:03 UTC, user424242420 commented
Наименование на скрине пофиксил

2024-05-26 12:22 UTC, Geliant commented
1. первый скрин
2. Второй скрин 
3. третий скрин
4. чётвёртый скрин 
5. пятый и шестой скрин 
6.  по наблюдениям , всё соответствует. 
В целом всё работает , но чтобы таймер обновился нужно закрыть и открыть кпк (если во время отзыва/вызыва шатла кпк был открыт) Также если не закрывать кпк , а шатл вызвали и отозвали , то таймер дойдёт до нуля и начнёт считать в обратную сторону(просто забавно)
![1](https://github.com/Corvax-Frontier/corvax-frontier-14/assets/160081925/a1d30b45-03a4-43f6-8ad6-305222e19481)
![3](https://github.com/Corvax-Frontier/corvax-frontier-14/assets/160081925/f1c2ba91-925e-4a6d-b2fb-552ca602819d)
![2](https://github.com/Corvax-Frontier/corvax-frontier-14/assets/160081925/a7f2e783-8476-43ac-b538-14f38944366c)
![4](https://github.com/Corvax-Frontier/corvax-frontier-14/assets/160081925/1d3a763b-008c-43d2-997c-5d7e51a2357d)
![5](https://github.com/Corvax-Frontier/corvax-frontier-14/assets/160081925/77e38f40-c9f3-4657-994d-d4c92dc46f5b)
![6](https://github.com/Corvax-Frontier/corvax-frontier-14/assets/160081925/b63c1aa3-b057-47af-a876-dce0e6bd4586)

2024-05-26 13:10 UTC, FireNameFN requested changes
Так. Пока что достаточно.

2024-05-26 13:10 UTC, FireNameFN commented on Content.Client/Options/UI/Tabs/NetworkTab.xaml.cs
> +            _cfg.SetCVar(CVars.NetPVSEntityExitBudget, (int)NetPvsLeaveSlider.Value);
Ну и нафига ты это сделал? По коду SS14 здесь должны быть пробелы.

2024-05-26 13:10 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +        private string _timeLeftShuttle = Loc.GetString("comp-pda-ui-unknown");
Не по порядку. Размести под `_alertLevel`.

2024-05-26 13:10 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +                    ("time", stationTime.ToString("hh\\:mm\\:ss"))));
Зачем-то добавил tab.

2024-05-26 13:10 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +            if (state.EvacShuttleTime != null)
`is not`

2024-05-26 13:10 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +            shuttleEvacTimeSpan = (state.EvacShuttleTime ?? TimeSpan.Zero);
Мог бы сначала вычислить `shuttleEvacTimeSpan`, а потом использовать его значение. Ненужные скобки.

2024-05-26 13:10 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +        /// 12</summary>
Чё?

2024-05-26 13:10 UTC, FireNameFN commented on Content.Server/PDA/PdaSystem.cs
> +                shuttleTime = new TimeSpan(0, 0, (int)(_cfg.GetCVar(CCVars.EmergencyShuttleDockTime) * 60));
`TimeSpan.FromMinutes()` или что там у тебя.

2024-05-26 13:10 UTC, FireNameFN commented on Content.Server/PDA/PdaSystem.cs
> +            if (!TryComp<StationEmergencyShuttleComponent>(station, out var stationEmergencyShuttleComponent) && _roundEndSystem.ExpectedCountdownEnd != null)
`is not`

2024-05-26 13:10 UTC, FireNameFN commented on Content.Shared/CCVar/CCVars.cs
> +            CVarDef.Create("explosion.max_area", (int)3.14f * 256 * 256, CVar.SERVERONLY);
Уъ сука.

2024-05-26 13:10 UTC, FireNameFN commented on Content.Shared/PDA/PdaUpdateState.cs
> +                                                                //AAAAAAAAAAAAAAAA
А это зачем?

2024-05-26 13:10 UTC, FireNameFN commented on Content.Server/PDA/PdaSystem.cs
> +            var station = _station.GetOwningStation(uid);
Возможен баг. Спрошу у тестировщика.

2024-05-26 13:10 UTC, FireNameFN commented on Content.Server/PDA/PdaSystem.cs
> +                shuttleTime = new TimeSpan(0, 0, (int)(_cfg.GetCVar(CCVars.EmergencyShuttleDockTime) * 60));
И лучше бы не писал `else`.

2024-05-26 13:21 UTC, FireNameFN commented on Content.Server/PDA/PdaSystem.cs
> +                shuttleTime = _roundEndSystem.ExpectedCountdownEnd ?? TimeSpan.Zero + _gameTiming.CurTime;
Подожди. Какой `??`? Ты ведь проверяешь на `null` в ифе.

2024-05-26 16:09 UTC, user424242420 commented on Content.Shared/CCVar/CCVars.cs
> +            CVarDef.Create("explosion.max_area", (int)3.14f * 256 * 256, CVar.SERVERONLY);
Это не я делаю а lsp

2024-05-26 16:09 UTC, user424242420 commented on Content.Server/PDA/PdaSystem.cs
> +                shuttleTime = _roundEndSystem.ExpectedCountdownEnd ?? TimeSpan.Zero + _gameTiming.CurTime;
Да но он мне не выдавал значение без ??

2024-05-26 16:12 UTC, user424242420 commented on Content.Shared/PDA/PdaUpdateState.cs
> +                                                                //AAAAAAAAAAAAAAAA
Lsp нихуя не знаю

2024-05-26 17:00 UTC, FireNameFN commented on Content.Server/PDA/PdaSystem.cs
> +                shuttleTime = _roundEndSystem.ExpectedCountdownEnd ?? TimeSpan.Zero + _gameTiming.CurTime;
`.Value` попробуй.

2024-05-29 13:17 UTC, user424242420 commented on Content.Client/Options/UI/Tabs/NetworkTab.xaml.cs
> +            _cfg.SetCVar(CVars.NetPVSEntityExitBudget, (int)NetPvsLeaveSlider.Value);
lsp знает лучше

2024-05-29 15:33 UTC, user424242420 commented
Теперь не надо перезаходить в кпк чтобы обновить данные

2024-05-30 04:07 UTC, FireNameFN requested changes

2024-05-30 04:07 UTC, ProtoFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +        private TimeSpan shuttleEvacTimeSpan;
Следует поставить это в другом месте

2024-05-30 04:07 UTC, ProtoFN commented on Content.Client/Options/UI/Tabs/NetworkTab.xaml.cs
> +            _cfg.SetCVar(CVars.NetPVSEntityExitBudget, (int)NetPvsLeaveSlider.Value);
Почини

2024-05-30 04:07 UTC, ProtoFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +                BalanceLabel.SetMarkup(_balance);
Ты же знаешь, что это не писон?

2024-05-30 04:07 UTC, ProtoFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +            ShuttleLeftTimeLabel.SetMarkup(_timeLeftShuttle);
Теперь у тебя это в двух местах написано. Убери верхнюю.

2024-05-30 04:07 UTC, FireNameFN commented on Content.Shared/CCVar/CCVars.cs
> +            CVarDef.Create("explosion.max_area", (int)3.14f * 256 * 256, CVar.SERVERONLY);
И это тоже.

2024-05-30 04:07 UTC, FireNameFN commented on Content.Shared/PDA/PdaUpdateState.cs
> +                                                                //AAAAAAAAAAAAAAAA
И это.

2024-05-30 04:07 UTC, FireNameFN commented on Content.Server/PDA/PdaSystem.cs
> +        [Dependency] private readonly IGameTiming _gameTiming = default!;
Кажется, оно не используется.

2024-05-30 04:07 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +                BalanceLabel.SetMarkup(_balance);
И лучше заменяй баланс на "Неизвестно", если он null.

2024-05-30 11:26 UTC, user424242420 commented on Content.Client/PDA/PdaMenu.xaml.cs
> +                BalanceLabel.SetMarkup(_balance);
Нет, потому что при обновлении принудительно при событии связанным с эваком он выдает null всегда

2024-05-30 11:27 UTC, user424242420 commented on Content.Client/Options/UI/Tabs/NetworkTab.xaml.cs
> +            _cfg.SetCVar(CVars.NetPVSEntityExitBudget, (int)NetPvsLeaveSlider.Value);
Что починить

2024-05-30 11:27 UTC, user424242420 commented on Content.Client/PDA/PdaMenu.xaml.cs
> +        private TimeSpan shuttleEvacTimeSpan;
В каком

2024-05-30 11:28 UTC, user424242420 commented on Content.Client/PDA/PdaMenu.xaml.cs
> +                BalanceLabel.SetMarkup(_balance);
Нет, потому что при обновлении принудительно при событии связанным с эваком он выдает null всегда

2024-05-31 05:04 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +        private TimeSpan shuttleEvacTimeSpan;
В 29-ой строчке. Не забудь сохранить ньюлайны.

2024-05-31 05:05 UTC, FireNameFN commented
Какой ревью реквест? Исправляй. Я анресолвнул всё, что надо исправить.

2024-05-31 14:54 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> -            if (state.Balance is not null)
Неправильно ты скобочки расставляешь.

2024-05-31 14:54 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> -            if (state.Balance is not null)
Блин, не та строчка. Но ты увидишь.

2024-05-31 17:42 UTC, FireNameFN requested changes

2024-05-31 17:42 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +                        ("time", stationTime.ToString("hh\\:mm\\:ss"))));
Лишний таб.

2024-05-31 17:42 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +            shuttleEvacTimeSpan = (state.EvacShuttleTime ?? TimeSpan.Zero);
Ненужные скобки.

2024-05-31 17:42 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +                        ("time", shuttleEvacTime.ToString("hh\\:mm\\:ss")));
Лишний таб.

2024-05-31 17:42 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +        private string _timeLeftShuttle = Loc.GetString("comp-pda-ui-unknown");
Переменные здесь нужны, если реализовано копирование по нажатию. Реализуй его.

2024-05-31 17:53 UTC, FireNameFN commented on Content.Server/PDA/PdaSystem.cs
> +using Robust.Shared.Timing;
Не используется.

2024-05-31 17:57 UTC, FireNameFN requested changes

2024-05-31 17:57 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> -
Верни.

2024-05-31 17:57 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +        private TimeSpan shuttleEvacTimeSpan;
Перенеси на 29-ую строчку.

2024-05-31 18:00 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +        private TimeSpan shuttleEvacTimeSpan;
Ну не так ведь. Чтобы была одна пустая строка до и столько же пустых строк, сколько было, то есть две, после.

2024-05-31 18:02 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
>          private TimeSpan shuttleEvacTimeSpan;
А строки после?

2024-05-31 18:07 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +
Две должно быть.

2024-05-31 18:10 UTC, ProtoFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> +
Видимо, ты не так вернул.

2024-05-31 18:13 UTC, FireNameFN commented on Content.Client/PDA/PdaMenu.xaml.cs
> -
Куда удалил? Надо было исправить.

2024-05-31 18:19 UTC, FireNameFN approved these changes

2024-05-31 18:53 UTC, merged